### ISSUE TITLE
AccessViolationException when passing string to .NET

### ISSUE THREAD

**Issue by ArunGust** [OpenByteDev/netcorehost#10]
Hi, 

I got below error, any idea to pass value to c# funciton
  
 Compiling nethost2 v0.1.0 ()
    Finished dev [unoptimized + debuginfo] target(s) in 1.41s
     Running `target\debug\nethost2.exe`
argLength 1
Hello, world! from Program [count: 1]
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.SpanHelpers.IndexOf(Char ByRef, Char, Int32)
   at System.String.Ctor(Char*)
   at System.Runtime.InteropServices.Marshal.PtrToStringUni(IntPtr)
   at Test.Program.PrintLibArgs(LibArgs)
   at Test.Program.Hello(IntPtr, Int32)
error: process didn't exit successfully: `target\debug\nethost2.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

**Comment by OpenByteDev** [comment]
Can you share your Rust and C# code?

**Comment by OpenByteDev** [comment]
It seems like you pass either a non null-terminated string or an utf8 string to Marshal.PtrToStringUni.

**Comment by ArunGust** [comment]
------rust code ------
pub fn foo() -> String {
    "test".to_string()
}

fn main() ->  Result<(), Box <dyn std::error::Error>> {
    let test_out_dir = Path::new("H:\\PUBLISH\\net5\\").absolutize()?;
    let runtime_config_path = Path::join(&test_out_dir, "Test.runtimeconfig.json");
    let assembly_path = Path::join(&test_out_dir, "Test.dll");

    let hostfxr = nethost::load_hostfxr()?;
    let context = hostfxr.initialize_for_runtime_config(PdCString::from_os_str(runtime_config_path)?)?;
    let mut fn_loader = context.get_delegate_loader_for_assembly(PdCString::from_os_str(assembly_path)?)?;
    let hello = fn_loader.get_function_pointer_with_default_signature(
        pdcstr!("Test.Program, Test"),
        pdcstr!("Hello"),
    )?;
    let pointer = foo as *const ();
    let result = unsafe {
        hello(pointer, 1)
    };
    println!("result is {:?}", result);
    Ok(())
}

**Comment by ArunGust** [comment]
---c# code---
        [StructLayout(LayoutKind.Sequential)]
        public struct LibArgs
        {
            public IntPtr Message;
        }
        public delegate int HelloFunc(IntPtr arg, int argLength);
        public static int Hello(IntPtr arg, int argLengt) {
            try
            {
                Console.WriteLine("argLength " + argLengt);
                LibArgs libArgs = Marshal.PtrToStructure<LibArgs>(arg);
                Console.WriteLine($"Hello, world! from {nameof(Program)} [count: {s_CallCount++}]");
                string message = RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
                    ? Marshal.PtrToStringUni(libArgs.Message) : Marshal.PtrToStringUTF8(libArgs.Message);
                Console.WriteLine($"-- message: {message}");
                CreateSpreadsheetWorkbook(@"formuploadtest22.xlsx");
                Console.WriteLine("Hello from C#");
                return 42;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message+ex.StackTrace);
                return 99;
            }
        }

**Comment by OpenByteDev** [comment]
You are passing a pointer to the function `foo` instead of the `String` instance it returns. It should probably be `foo().as_ptr() as *const ()`

**Comment by ArunGust** [comment]
Thank you, kept struct for passing additional variables . Let me try, but foo().as_ptr() as *const (). didnt solve the issue

**Comment by ArunGust** [comment]
Thank you worked
----
`    let c_string = CString::new("testing something").expect("CString::new failed");
    let ptr = c_string.into_raw();
    let _pointer = ptr as *const ();

    let result = unsafe {
        hello(_pointer, 1)
    };
`

**Comment by ArunGust** [comment]
Thanks, Marshal.PtrToStringUTF8 and CString combination worked

```
let c_string = CString::new("testing something").expect("CString::new failed");
let ptr = c_string.into_raw();
let _pointer = ptr as *const ();

let result = unsafe {
    hello(_pointer, 1)
};

```

**Comment by OpenByteDev** [comment]
Beware that your current code never deallocates `c_string`.
