### ISSUE TITLE
could not find `u16cstr` in the list of imported crates

### ISSUE THREAD

**Issue by ArunGust** [OpenByteDev/netcorehost#12]
Any idea why this error  ?  
--> src\main.rs:17:9
   |
17 |         pdcstr!("Test.Program, Test"),
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `u16cstr` in the list of imported crates
   |
   = note: this error originates in the macro `pdcstr` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by ArunGust** [comment]
Worked after changing cargo.toml to 

netcorehost = "0.3.1"
path-absolutize = "3.0.10"
wchar = "0.10.1"

**Comment by OpenByteDev** [comment]
What was your Cargo.toml previously?

**Comment by ArunGust** [comment]
netcorehost = "^0.4.0"
path-absolutize = "^3.0.10"
wchar = "^0.10.1"
