### ISSUE TITLE
Initialization request is expected to be non-null for requests other than the first one

### ISSUE THREAD

**Issue by ArunGust** [OpenByteDev/netcorehost#13]
I got this error from 2nd time

Initialization request is expected to be non-null for requests other than the first one
Failed to initialize context for config: D:\net5\Test.runtimeconfig.json. Error code: 0x80008081

**Comment by OpenByteDev** [comment]
Can you share your code?

**Comment by ArunGust** [comment]
Here it is 

`
fn main() ->  Result<(), Box <dyn std::error::Error>> {

    let mut values = json::JsonValue::new_object();
    values["name"] = "arun".to_string().into();
    values["age"] = "32".to_string().into();
    let mut requestdetails = json::JsonValue::new_object();
    requestdetails["fname"] = "test1234".to_string().into();
    requestdetails["sname"] =  "test1234".to_string().into();
    requestdetails["data"] = format!("[{}]",values.clone()).to_string().into();

    let _ = helloddl(requestdetails);

    let mut requestdetails2 = json::JsonValue::new_object();
    requestdetails2["fname"] = "test123456".to_string().into();
    requestdetails2["sname"] =  "test123456".to_string().into();
    requestdetails2["data"] = format!("[{}]",values).to_string().into();
    let _ = helloddl( requestdetails2);

    Ok(())
}

pub fn helloddl(jsonstring: json::JsonValue) -> core::result::Result<(), Box<dyn std::error::Error>> {
    let test_out_dir = Path::new("D:\\net5\\").absolutize()?;
    let runtime_config_path = Path::join(&test_out_dir, "Test.runtimeconfig.json");
    let assembly_path = Path::join(&test_out_dir, "Test.dll");

    let hostfxr = nethost::load_hostfxr()?;
    let context = hostfxr.initialize_for_runtime_config(PdCString::from_os_str(runtime_config_path)?)?;
    let mut fn_loader = context.get_delegate_loader_for_assembly(PdCString::from_os_str(assembly_path)?)?;
    let hello = fn_loader.get_function_pointer_with_default_signature(
        pdcstr!("Test.Program, Test"),
        pdcstr!("Hello"),
    )?;

    let c_string = CString::new(jsonstring.to_string()).expect("CString::new failed");
    let ptr = c_string.into_raw();
    let _pointer = ptr as *const ();

    let result = unsafe {
        hello(_pointer, 1)
    };
    println!("result is {:?}", result);    
    Ok(())
}`

**Comment by ArunGust** [comment]
2nd call causing error.

**Comment by ArunGust** [comment]
**Worked after changed to** 




fn main() -> Result<(), Box > {

let test_out_dir = Path::new("D:\net5\").absolutize()?;
let runtime_config_path = Path::join(&test_out_dir, "Test.runtimeconfig.json");
let assembly_path = Path::join(&test_out_dir, "Test.dll");

let hostfxr = nethost::load_hostfxr()?;
let context = hostfxr.initialize_for_runtime_config(PdCString::from_os_str(runtime_config_path)?)?;
let mut fn_loader = context.get_delegate_loader_for_assembly(PdCString::from_os_str(assembly_path)?)?;
let hello = fn_loader.get_function_pointer_with_default_signature(
    pdcstr!("Test.Program, Test"),
    pdcstr!("Hello"),
)?;

let mut values = json::JsonValue::new_object();
values["name"] = "arun".to_string().into();
values["age"] = "32".to_string().into();
let mut requestdetails = json::JsonValue::new_object();
requestdetails["fname"] = "test1234".to_string().into();
requestdetails["sname"] =  "test1234".to_string().into();
requestdetails["data"] = format!("[{}]",values.clone()).to_string().into();

let _ = helloddl(requestdetails);

let mut requestdetails2 = json::JsonValue::new_object();
requestdetails2["fname"] = "test123456".to_string().into();
requestdetails2["sname"] =  "test123456".to_string().into();
requestdetails2["data"] = format!("[{}]",values).to_string().into();
let _ = helloddl( requestdetails2);

Ok(())
}

pub fn helloddl(mut fn_loader: AssemblyDelegateLoader<PdCString>, jsonstring: json::JsonValue) -> core::result::Result<(), Box<dyn std::error::Error>> {

    let hello = fn_loader.get_function_pointer_with_default_signature(
        pdcstr!("Test.Program, Test"),
        pdcstr!("Hello"),
    )?;

let c_string = CString::new(jsonstring.to_string()).expect("CString::new failed");
let ptr = c_string.into_raw();
let _pointer = ptr as *const ();

let result = unsafe {
    hello(_pointer, 1)
};
println!("result is {:?}", result);    
Ok(())
}`
