### ISSUE TITLE
error[E0433]: failed to resolve: use of undeclared crate or module `cstr`   --> src/nethostexcel.rs:69:13

### ISSUE THREAD

**Issue by ArunGust** [OpenByteDev/netcorehost#14]
**I got below error in my ubunutu box**

error[E0433]: failed to resolve: use of undeclared crate or module `cstr`
  --> src/nethostexcel.rs:69:13
   |
69 |             pdcstr!("test"),
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `cstr`
   |
   = note: this error originates in the macro `pdcstr` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by OpenByteDev** [comment]
Which version are you using?

**Comment by ArunGust** [comment]
rustc 1.57.0-nightly (e30b68353 2021-09-05)
cargo 1.56.0-nightly (18751dd3f 2021-09-01)

**Comment by OpenByteDev** [comment]
And what version of netcorehost?

**Comment by ArunGust** [comment]
netcorehost = "^0.3.1"

**Comment by ArunGust** [comment]
netcorehost = "^0.3.1"
path-absolutize = "3.0.10"
wchar = "0.10.1"

**Comment by OpenByteDev** [comment]
The bug should be fixed since 897840285915c9bd541ed3d4313cc5b17957519a alongside #12. Try a version >= 0.5.0, 0.6.4 should be the best choice as its the newest.

**Comment by ArunGust** [comment]
tried 0.6.4

^^^^^^^^ expected enum `c_void`, found `()`
   |
49 |         hello(_pointer, 1)
   |               ^^^^^^^^ expected enum `c_void`, found `()`
   |
   = note: expected raw pointer `*const c_void`
              found raw pointer `*const ()`

**Comment by OpenByteDev** [comment]
You probably only need to change some occurance of `*const ()` to `*const std::ffi::c_void`. You can also take a look at the updates examples.

**Comment by ArunGust** [comment]
i wanted to pass data to DLL

**Comment by ArunGust** [comment]
sample code 

    let c_string = CString::new("pass string".to_string()).expect("CString::new failed");
    let ptr = c_string.into_raw();
    let _pointer = ptr as *const ();

    let result = unsafe {
        hello(_pointer, 1)
    };

**Comment by ArunGust** [comment]
worked after adding cstr = "0.2.8" to toml and keeping verison 0.3.0

**Comment by OpenByteDev** [comment]
You just need to replace the `*const ()` to `*const std::ffi::c_void` on the third line.
