### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Hostfxr(Known(CoreHostLibMissingFailure))',

### ISSUE THREAD

**Issue by ArunGust** [OpenByteDev/netcorehost#15]
I got this error  from ubuntu

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Hostfxr(Known(CoreHostLibMissingFailure))',

I have added linux-64 folder as target folder to pickup dll

Any idea ?

**Comment by ArunGust** [comment]
error changed below after installing SDK

Initialization for self-contained components is not supported
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Hostfxr(Known(InvalidConfigFile))'

**Comment by ArunGust** [comment]
Never mind, it worked after i use dll compiled for windows

**Comment by BadRyuner** [comment]
Can you tell me more about how you fixed the error? I have the same exception when I use "hostfxr.initialize_for_runtime_config".
