### ISSUE TITLE
Example on how to return a string from Dotnet

### ISSUE THREAD

**Issue by kt215** [OpenByteDev/netcorehost#18]
Do you have an example on how to return a string from a Dotnet method?

I want to send JSON (string) data back and forth between Rust and Dotnet.

**Comment by OpenByteDev** [comment]
Have a look at the [return-string-from-managed example](https://github.com/OpenByteDev/netcorehost/tree/master/examples/return-string-from-managed), especially method 1 and 4.

**Comment by kt215** [comment]
Awesome work, thanks! Yes, method 1 and 4 appears to have the least amount of boilerplate and code I can (barely) understand :-) I'm still learning rust, but this looks promising.
