### ISSUE TITLE
How to call something like Powershell from the CLR?

### ISSUE THREAD

**Issue by TheOnlyArtz** [OpenByteDev/netcorehost#19]
This library seems amazing, I would like to know how (if possible) I can use it to: 
• Load the System.Management.Automation library.
• Create a runspace and invoke powershell commands/scripts

**Comment by OpenByteDev** [comment]
I have no experience with `System.Management.Automation`, but in principle you should be able to do basically everything you can do in a normal .NET program.

**Comment by OpenByteDev** [comment]
I think the easiest solution is to write a library youself that then uses the Microsoft library.

**Comment by TheOnlyArtz** [comment]
@OpenByteDev I did but I can't dynamically link it(?) Without touching the disk

**Comment by OpenByteDev** [comment]
I dont know if there is an API for manual dll loading, but if there is it is currently not covered by this crate.

**Comment by TheOnlyArtz** [comment]
Ok then, thank you.
