### ISSUE TITLE
Executing from Bytes instead of from Disk

### ISSUE THREAD

**Issue by fetzsav** [OpenByteDev/netcorehost#24]
There is a Load method from which you can load an assembly from Bytes in memory versus having the path on disk. I have been unable to find support for this in this crate. Are there any plans for this, or is there anyway it is already possible?

**Comment by OpenByteDev** [comment]
I think the appropriate API is only available in `hostpolicy` (i think), while this crate only uses `hostfxr`.

**Comment by OpenByteDev** [comment]
This was added with .NET 8: https://github.com/dotnet/runtime/blob/main/docs/design/features/native-hosting.md#loading-managed-components-net-8-and-above

**Comment by OpenByteDev** [comment]
Implemented in 5c3e985dab37981fb944417c3bbc8f9fd4637ea4

**Comment by OpenByteDev** [comment]
Published in [0.15.0](https://crates.io/crates/netcorehost/0.15.0)
