### ISSUE TITLE
Error: proc-macro derive panicked

### ISSUE THREAD

**Issue by Scaum** [OpenByteDev/netcorehost#26]
Hello, I unable to build this after applying the fix described here: https://github.com/OpenByteDev/netcorehost/issues/25

The error linked to nethost-sys is now fixed, but I still get an error linked to hostfxr-sys:

![image](https://user-images.githubusercontent.com/9824789/204503434-986ee0d8-6b6f-405e-a852-7c1f5c7dcc27.png)

   Compiling hostfxr-sys v0.5.0
   Compiling XXX v0.1.0 (xxxxxxx)
   Compiling nethost-sys v0.6.1 (https://github.com/OpenByteDev/nethost-sys#3bae0526)
error: proc-macro derive panicked
   --> C:\Users\xxxxx\hostfxr-sys-0.5.0\src\lib.rs:232:22
    |
232 |               #[derive(WrapperApi)]
    |                        ^^^^^^^^^^
...
243 | / derive_apis! {
244 | |     pub struct Hostfxr {
245 | |         /// Run an application.
246 | |         ///
...   |
676 | |     }
677 | | }
    | |_- in this macro invocation 
    |
    = help: message: Only bare functions, references and pointers are allowed in structures implementing WrapperApi trait
    = note: this error originates in the macro 'derive_apis' (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile 'hostfxr-sys' due to previous error

Would you have an idea how to fix this ?

**Comment by OpenByteDev** [comment]
Can you try to directly use `hostfxr-sys`?

**Comment by Scaum** [comment]
Same issue, cannot build hostfxr-sys if I clone it.

I managed to build by cloning hostfxr-sys, doing a checkout to commit f9c7c59, changing the version in Cargo.toml back to 0.5.0 and linking my local folder as the dependency. However even if it builds I have a rust_panic when I try launching a simple Hello World .NET app

![image](https://user-images.githubusercontent.com/9824789/204541883-4d8ee06e-05ab-4ba3-b5d3-b6f155e74ce0.png)

**Comment by OpenByteDev** [comment]
What version of rust are you using?

**Comment by OpenByteDev** [comment]
Does it work without the fix? (As it should not be required anymore)

**Comment by DmitryHudrich** [comment]
oh no, not works only on nightly rust
