### ISSUE TITLE
Cross-compilation linking error for x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by asiryk** [OpenByteDev/netcorehost#29]
This is probably not a problem with netcorehost library itself because it compiles on windows with no problem. However, I've tried to cross-compile the library from MacOS to Windows using [cross-rs](https://github.com/cross-rs/cross) project.

I submitted [this issue](https://github.com/cross-rs/cross/issues/1211), and the [maintainer said](https://github.com/cross-rs/cross/issues/1211#issuecomment-1437318546):

> I think the issue is the distribution.

Probably you could suggest how to work through this issue?

**Comment by OpenByteDev** [comment]
The nethost library is built using msvc and does not support the gnu toolchain. (https://github.com/dotnet/runtime/issues/81751)
