### ISSUE TITLE
Call rust functions using the extern keyword?

### ISSUE THREAD

**Issue by Stay1444** [OpenByteDev/netcorehost#30]
Can i define rust functions in the dotnet host so that C# code can access them using the `extern` keyword?

```rs
pub fn some_func() { }
```

```cs
public static extern void some_func();
```

Is this possible?

**Comment by OpenByteDev** [comment]
Yes thats possible, have a look at https://github.com/OpenByteDev/netcorehost/tree/OpenByteDev-patch-1/examples/return-string-from-managed
