### ISSUE TITLE
Why `and Delegate Loaded don't implement the send trait ?

### ISSUE THREAD

**Issue by D3lta-2-1** [OpenByteDev/netcorehost#33]
My apologies, I've just seen I wrote the title a little to fast, I'm talking about ``DelegateLoader`` and ``HostfxrContext<>``.

Since my application heavly rely on C# interop, I would like to load CoreClr at static time, I tried to work around by using ``Arc<>`` and ``Mutex<>`` but there is no way to put ``HostfxrContext`` in LazyLock ? (or a [ctor] from ctor crate) ?

**Comment by OpenByteDev** [comment]
Because the context is not thread safe according to one of the documents linkwd in the readme

**Comment by OpenByteDev** [comment]
Okay, quickly looking over the docs again, it seems the context only has to be !Sync but could be Send.

**Comment by D3lta-2-1** [comment]
```rust
#[derive(DestructDrop)]
#[cfg_attr(feature = "doc-cfg", doc(cfg(feature = "netcore3_0")))]
pub struct HostfxrContext<I> {
    handle: HostfxrHandle,
    hostfxr: SharedHostfxrLibrary,
    is_primary: bool,
    runtime_delegates: EnumMap<hostfxr_delegate_type, OnceCell<RawFunctionPtr>>,
    context_type: PhantomData<I>, 
    not_thread_safe: PhantomData<Rc<HostfxrLibrary>>, //could Rc<> be changed for Arc<> ?
}```
