### ISSUE TITLE
error[E0554]: `#![feature]` may not be used on the stable release channel

### ISSUE THREAD

**Issue by ArunGust** [OpenByteDev/netcorehost#8]
Hey ,

I got below error , any suggession ?

   Compiling netcorehost v0.3.1
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> D:\RUST\CARGO\registry\src\github.com-1ecc6299db9ec823\netcorehost-0.3.1\src\lib.rs:1:1
  |
1 | / #![feature(
2 | |     maybe_uninit_uninit_array,
3 | |     maybe_uninit_extra,
4 | |     maybe_uninit_slice,
5 | |     negative_impls
6 | | )]
  | |__^

error: aborting due to previous error

**Comment by OpenByteDev** [comment]
These features represent nightly only functionality, which means that `netcorehost` will only compile with the nightly toolchain.

You are currently on stable. You can switch to nightly with `rustup override set nightly`.

May be helpful:
- https://doc.rust-lang.org/rustdoc/unstable-features.html
- https://doc.rust-lang.org/book/appendix-07-nightly-rust.html

**Comment by ArunGust** [comment]
thanks, it worked
